### ISSUE TITLE
InvalidCastException: Cannot cast from source type to destination type.

### ISSUE THREAD

**Issue by robotron2084** [PlayFab/PlayFab-Samples#6]
In ProgressiveRewards.cs the line:

		List<ItemInstance> grantedItems = (List<ItemInstance>)result.FunctionResult;

Throws an exception:
InvalidCastException: Cannot cast from source type to destination type.

When looking at the contents of result.FunctionResult it was a List<System.Object>. It did not seem to matter whether or not items were being granted (ie whether there were items in the list).

I am using the .unitypackage from here:
https://github.com/PlayFab/UnitySDK/blob/master/PlayFabClientSDK.unitypackage

`public const string VersionString = "UnitySDK-0.32.160711";`

Any ideas on how I can fix this?
Thanks

**Comment by robotron2084** [comment]
More information is available here and a potential solution in my answer:

https://community.playfab.com/questions/3816/list-is-returned-as-list.html#comment-3829

**Comment by zac-playfab** [comment]
Yep this is now updated to the correct deserialization syntax.
