### ISSUE TITLE
Sample Login Screen went MIA

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/PlayFab-Samples#7]
Where did this go :) The original repo says "depreciated", but no other one was replaced. Would be nice to even see the obsolete one as a simple reference

**Comment by zac-playfab** [comment]
Hopefully we will have a new login example out that shows a really robust account management scenario. Until then the master branch still has all of the original code: https://github.com/PlayFab/Unity3d_Login_Example_Project/tree/master
